package com.cros.vue.mapper;

import com.cros.vue.entity.Customer;
import com.cros.vue.entity.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface CustomerMapper {
    @SelectProvider(type=CustomerSqlProvider.class, method="countByExample")
    long countByExample(CustomerExample example);

    @DeleteProvider(type=CustomerSqlProvider.class, method="deleteByExample")
    int deleteByExample(CustomerExample example);

    @Delete({
        "delete from C_CUSTOMER",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into C_CUSTOMER (ID, AD_CLIENT_ID, ",
        "AD_ORG_ID, MODIFIERID, ",
        "CREATIONDATE, MODIFIEDDATE, ",
        "OWNERID, ISACTIVE, ",
        "NAME, DESCRIPTION, ",
        "ENTERDATE, ISSTOP, ",
        "CONTACTER, PHONE, ",
        "ADDRESS, POST, ACCOUNT, ",
        "EMAIL, REMARK, TAXNO, ",
        "FEEREMAIN, FEESALE, ",
        "SALEDIS, SALERETDIS, ",
        "C_CUSRANK_ID, C_CUSTOMERUP_ID, ",
        "FIRSALEDIS, FEELSALE, ",
        "FEELTAKE, ISPERIOD, ",
        "AREAMNG_ID, C_CITY_ID, ",
        "ISAUTOIN, ORDERRATE, ",
        "RET_RATE, BIGAREAMNG_ID, ",
        "ISGROUP, ISACCOUNT, C_DEPARTMENT_ID, ",
        "C_CLASSCODE_ID, CODE, ",
        "C_AREA_ID, PRIORITY, ",
        "M_DIMCUS1_ID, M_DIMCUS2_ID, ",
        "M_DIMCUS3_ID, M_DIMCUS4_ID, ",
        "M_DIMCUS5_ID, M_DIMCUS6_ID, ",
        "M_DIMCUS7_ID, M_DIMCUS8_ID, ",
        "M_DIMCUS9_ID, M_DIMCUS10_ID, ",
        "BUTSALEDIS, AGTSALEDIS, ",
        "FIRSALERETDIS, AGTSALERETDIS, ",
        "TRANDIS, C_CUSATTRIB1_ID, ",
        "C_CUSATTRIB2_ID, C_CUSATTRIB3_ID, ",
        "C_CUSATTRIB4_ID, C_CUSATTRIB5_ID, ",
        "C_CUSATTRIB6_ID, C_CUSATTRIB7_ID, ",
        "C_CUSATTRIB8_ID, C_CUSATTRIB9_ID, ",
        "C_CUSATTRIB10_ID, C_CUSATTRIB11_ID, ",
        "C_CUSATTRIB12_ID, C_CUSATTRIB13_ID, ",
        "C_CUSATTRIB14_ID, C_CUSATTRIB15_ID, ",
        "C_CUSATTRIB16_ID, C_CUSATTRIB17_ID, ",
        "C_CUSATTRIB18_ID, C_CUSATTRIB19_ID, ",
        "C_CUSATTRIB20_ID, CAN_BUTSALE, ",
        "CAN_NOTBUTSALE, CAN_AGTSALE, ",
        "ISCREFUND, C_CUSTYPE_ID, ",
        "M_DIM1_ID, MOBILE, ",
        "CALCULATION, ISKD, ",
        "LEGAL_ID, FIRRETRATE, ",
        "RETRATE, AGTRETRATE, ",
        "GL_COMPANY, PROFITCENTER, ",
        "ISTHIRD, LEGAL, IS_PCK, ",
        "IS_SALE_PCK, IS_RETPUT_PCK, ",
        "IMGURL1, IMGURL2, ",
        "IMGURL3, IMGURL4, ",
        "IMGURL5, B_CUSCODE_FORMAT_ID, ",
        "SALEINVITEM, C_FRANCHISEE_ID, ",
        "C_CUSGROUP_ID, BANK, ",
        "C_CURRENCY_ID, PAYWAY, ",
        "TRADEWAY, BIRTHDAY, ",
        "FRANCHISEE_RELASHIP, OPENSTORE_TYPE, ",
        "STOPDATE, C_BRANCH_ID, ",
        "C_SALER_ID, SALESREP_ID)",
        "values (#{id,jdbcType=NUMERIC}, #{adClientId,jdbcType=NUMERIC}, ",
        "#{adOrgId,jdbcType=NUMERIC}, #{modifierid,jdbcType=NUMERIC}, ",
        "#{creationdate,jdbcType=TIMESTAMP}, #{modifieddate,jdbcType=TIMESTAMP}, ",
        "#{ownerid,jdbcType=NUMERIC}, #{isactive,jdbcType=CHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{enterdate,jdbcType=NUMERIC}, #{isstop,jdbcType=CHAR}, ",
        "#{contacter,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{post,jdbcType=VARCHAR}, #{account,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, #{taxno,jdbcType=VARCHAR}, ",
        "#{feeremain,jdbcType=NUMERIC}, #{feesale,jdbcType=NUMERIC}, ",
        "#{saledis,jdbcType=NUMERIC}, #{saleretdis,jdbcType=NUMERIC}, ",
        "#{cCusrankId,jdbcType=NUMERIC}, #{cCustomerupId,jdbcType=NUMERIC}, ",
        "#{firsaledis,jdbcType=NUMERIC}, #{feelsale,jdbcType=NUMERIC}, ",
        "#{feeltake,jdbcType=NUMERIC}, #{isperiod,jdbcType=CHAR}, ",
        "#{areamngId,jdbcType=NUMERIC}, #{cCityId,jdbcType=NUMERIC}, ",
        "#{isautoin,jdbcType=CHAR}, #{orderrate,jdbcType=NUMERIC}, ",
        "#{retRate,jdbcType=NUMERIC}, #{bigareamngId,jdbcType=NUMERIC}, ",
        "#{isgroup,jdbcType=CHAR}, #{isaccount,jdbcType=CHAR}, #{cDepartmentId,jdbcType=NUMERIC}, ",
        "#{cClasscodeId,jdbcType=NUMERIC}, #{code,jdbcType=VARCHAR}, ",
        "#{cAreaId,jdbcType=NUMERIC}, #{priority,jdbcType=NUMERIC}, ",
        "#{mDimcus1Id,jdbcType=NUMERIC}, #{mDimcus2Id,jdbcType=NUMERIC}, ",
        "#{mDimcus3Id,jdbcType=NUMERIC}, #{mDimcus4Id,jdbcType=NUMERIC}, ",
        "#{mDimcus5Id,jdbcType=NUMERIC}, #{mDimcus6Id,jdbcType=NUMERIC}, ",
        "#{mDimcus7Id,jdbcType=NUMERIC}, #{mDimcus8Id,jdbcType=NUMERIC}, ",
        "#{mDimcus9Id,jdbcType=NUMERIC}, #{mDimcus10Id,jdbcType=NUMERIC}, ",
        "#{butsaledis,jdbcType=NUMERIC}, #{agtsaledis,jdbcType=NUMERIC}, ",
        "#{firsaleretdis,jdbcType=NUMERIC}, #{agtsaleretdis,jdbcType=NUMERIC}, ",
        "#{trandis,jdbcType=NUMERIC}, #{cCusattrib1Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib2Id,jdbcType=NUMERIC}, #{cCusattrib3Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib4Id,jdbcType=NUMERIC}, #{cCusattrib5Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib6Id,jdbcType=NUMERIC}, #{cCusattrib7Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib8Id,jdbcType=NUMERIC}, #{cCusattrib9Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib10Id,jdbcType=NUMERIC}, #{cCusattrib11Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib12Id,jdbcType=NUMERIC}, #{cCusattrib13Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib14Id,jdbcType=NUMERIC}, #{cCusattrib15Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib16Id,jdbcType=NUMERIC}, #{cCusattrib17Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib18Id,jdbcType=NUMERIC}, #{cCusattrib19Id,jdbcType=NUMERIC}, ",
        "#{cCusattrib20Id,jdbcType=NUMERIC}, #{canButsale,jdbcType=CHAR}, ",
        "#{canNotbutsale,jdbcType=CHAR}, #{canAgtsale,jdbcType=CHAR}, ",
        "#{iscrefund,jdbcType=VARCHAR}, #{cCustypeId,jdbcType=NUMERIC}, ",
        "#{mDim1Id,jdbcType=NUMERIC}, #{mobile,jdbcType=VARCHAR}, ",
        "#{calculation,jdbcType=NUMERIC}, #{iskd,jdbcType=CHAR}, ",
        "#{legalId,jdbcType=NUMERIC}, #{firretrate,jdbcType=NUMERIC}, ",
        "#{retrate,jdbcType=NUMERIC}, #{agtretrate,jdbcType=NUMERIC}, ",
        "#{glCompany,jdbcType=VARCHAR}, #{profitcenter,jdbcType=VARCHAR}, ",
        "#{isthird,jdbcType=CHAR}, #{legal,jdbcType=VARCHAR}, #{isPck,jdbcType=CHAR}, ",
        "#{isSalePck,jdbcType=CHAR}, #{isRetputPck,jdbcType=CHAR}, ",
        "#{imgurl1,jdbcType=VARCHAR}, #{imgurl2,jdbcType=VARCHAR}, ",
        "#{imgurl3,jdbcType=VARCHAR}, #{imgurl4,jdbcType=VARCHAR}, ",
        "#{imgurl5,jdbcType=VARCHAR}, #{bCuscodeFormatId,jdbcType=NUMERIC}, ",
        "#{saleinvitem,jdbcType=CHAR}, #{cFranchiseeId,jdbcType=NUMERIC}, ",
        "#{cCusgroupId,jdbcType=NUMERIC}, #{bank,jdbcType=VARCHAR}, ",
        "#{cCurrencyId,jdbcType=NUMERIC}, #{payway,jdbcType=CHAR}, ",
        "#{tradeway,jdbcType=CHAR}, #{birthday,jdbcType=NUMERIC}, ",
        "#{franchiseeRelaship,jdbcType=CHAR}, #{openstoreType,jdbcType=CHAR}, ",
        "#{stopdate,jdbcType=TIMESTAMP}, #{cBranchId,jdbcType=NUMERIC}, ",
        "#{cSalerId,jdbcType=NUMERIC}, #{salesrepId,jdbcType=NUMERIC})"
    })
    int insert(Customer record);



    @SelectProvider(type=CustomerSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="AD_CLIENT_ID", property="adClientId", jdbcType=JdbcType.NUMERIC),
        @Result(column="AD_ORG_ID", property="adOrgId", jdbcType=JdbcType.NUMERIC),
        @Result(column="MODIFIERID", property="modifierid", jdbcType=JdbcType.NUMERIC),
        @Result(column="CREATIONDATE", property="creationdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFIEDDATE", property="modifieddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="OWNERID", property="ownerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISACTIVE", property="isactive", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="ENTERDATE", property="enterdate", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISSTOP", property="isstop", jdbcType=JdbcType.CHAR),
        @Result(column="CONTACTER", property="contacter", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHONE", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST", property="post", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCOUNT", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="TAXNO", property="taxno", jdbcType=JdbcType.VARCHAR),
        @Result(column="FEEREMAIN", property="feeremain", jdbcType=JdbcType.NUMERIC),
        @Result(column="FEESALE", property="feesale", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALEDIS", property="saledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALERETDIS", property="saleretdis", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSRANK_ID", property="cCusrankId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSTOMERUP_ID", property="cCustomerupId", jdbcType=JdbcType.NUMERIC),
        @Result(column="FIRSALEDIS", property="firsaledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="FEELSALE", property="feelsale", jdbcType=JdbcType.NUMERIC),
        @Result(column="FEELTAKE", property="feeltake", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISPERIOD", property="isperiod", jdbcType=JdbcType.CHAR),
        @Result(column="AREAMNG_ID", property="areamngId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CITY_ID", property="cCityId", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISAUTOIN", property="isautoin", jdbcType=JdbcType.CHAR),
        @Result(column="ORDERRATE", property="orderrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="RET_RATE", property="retRate", jdbcType=JdbcType.NUMERIC),
        @Result(column="BIGAREAMNG_ID", property="bigareamngId", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISGROUP", property="isgroup", jdbcType=JdbcType.CHAR),
        @Result(column="ISACCOUNT", property="isaccount", jdbcType=JdbcType.CHAR),
        @Result(column="C_DEPARTMENT_ID", property="cDepartmentId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CLASSCODE_ID", property="cClasscodeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_AREA_ID", property="cAreaId", jdbcType=JdbcType.NUMERIC),
        @Result(column="PRIORITY", property="priority", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS1_ID", property="mDimcus1Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS2_ID", property="mDimcus2Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS3_ID", property="mDimcus3Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS4_ID", property="mDimcus4Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS5_ID", property="mDimcus5Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS6_ID", property="mDimcus6Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS7_ID", property="mDimcus7Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS8_ID", property="mDimcus8Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS9_ID", property="mDimcus9Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS10_ID", property="mDimcus10Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="BUTSALEDIS", property="butsaledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="AGTSALEDIS", property="agtsaledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="FIRSALERETDIS", property="firsaleretdis", jdbcType=JdbcType.NUMERIC),
        @Result(column="AGTSALERETDIS", property="agtsaleretdis", jdbcType=JdbcType.NUMERIC),
        @Result(column="TRANDIS", property="trandis", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB1_ID", property="cCusattrib1Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB2_ID", property="cCusattrib2Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB3_ID", property="cCusattrib3Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB4_ID", property="cCusattrib4Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB5_ID", property="cCusattrib5Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB6_ID", property="cCusattrib6Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB7_ID", property="cCusattrib7Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB8_ID", property="cCusattrib8Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB9_ID", property="cCusattrib9Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB10_ID", property="cCusattrib10Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB11_ID", property="cCusattrib11Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB12_ID", property="cCusattrib12Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB13_ID", property="cCusattrib13Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB14_ID", property="cCusattrib14Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB15_ID", property="cCusattrib15Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB16_ID", property="cCusattrib16Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB17_ID", property="cCusattrib17Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB18_ID", property="cCusattrib18Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB19_ID", property="cCusattrib19Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB20_ID", property="cCusattrib20Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="CAN_BUTSALE", property="canButsale", jdbcType=JdbcType.CHAR),
        @Result(column="CAN_NOTBUTSALE", property="canNotbutsale", jdbcType=JdbcType.CHAR),
        @Result(column="CAN_AGTSALE", property="canAgtsale", jdbcType=JdbcType.CHAR),
        @Result(column="ISCREFUND", property="iscrefund", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_CUSTYPE_ID", property="cCustypeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIM1_ID", property="mDim1Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="CALCULATION", property="calculation", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISKD", property="iskd", jdbcType=JdbcType.CHAR),
        @Result(column="LEGAL_ID", property="legalId", jdbcType=JdbcType.NUMERIC),
        @Result(column="FIRRETRATE", property="firretrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="RETRATE", property="retrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="AGTRETRATE", property="agtretrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="GL_COMPANY", property="glCompany", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROFITCENTER", property="profitcenter", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISTHIRD", property="isthird", jdbcType=JdbcType.CHAR),
        @Result(column="LEGAL", property="legal", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_PCK", property="isPck", jdbcType=JdbcType.CHAR),
        @Result(column="IS_SALE_PCK", property="isSalePck", jdbcType=JdbcType.CHAR),
        @Result(column="IS_RETPUT_PCK", property="isRetputPck", jdbcType=JdbcType.CHAR),
        @Result(column="IMGURL1", property="imgurl1", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL2", property="imgurl2", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL3", property="imgurl3", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL4", property="imgurl4", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL5", property="imgurl5", jdbcType=JdbcType.VARCHAR),
        @Result(column="B_CUSCODE_FORMAT_ID", property="bCuscodeFormatId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALEINVITEM", property="saleinvitem", jdbcType=JdbcType.CHAR),
        @Result(column="C_FRANCHISEE_ID", property="cFranchiseeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSGROUP_ID", property="cCusgroupId", jdbcType=JdbcType.NUMERIC),
        @Result(column="BANK", property="bank", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_CURRENCY_ID", property="cCurrencyId", jdbcType=JdbcType.NUMERIC),
        @Result(column="PAYWAY", property="payway", jdbcType=JdbcType.CHAR),
        @Result(column="TRADEWAY", property="tradeway", jdbcType=JdbcType.CHAR),
        @Result(column="BIRTHDAY", property="birthday", jdbcType=JdbcType.NUMERIC),
        @Result(column="FRANCHISEE_RELASHIP", property="franchiseeRelaship", jdbcType=JdbcType.CHAR),
        @Result(column="OPENSTORE_TYPE", property="openstoreType", jdbcType=JdbcType.CHAR),
        @Result(column="STOPDATE", property="stopdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="C_BRANCH_ID", property="cBranchId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_SALER_ID", property="cSalerId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALESREP_ID", property="salesrepId", jdbcType=JdbcType.NUMERIC)
    })
    List<Customer> selectByExample(CustomerExample example);

    @Select({
        "select",
        "ID, AD_CLIENT_ID, AD_ORG_ID, MODIFIERID, CREATIONDATE, MODIFIEDDATE, OWNERID, ",
        "ISACTIVE, NAME, DESCRIPTION, ENTERDATE, ISSTOP, CONTACTER, PHONE, ADDRESS, POST, ",
        "ACCOUNT, EMAIL, REMARK, TAXNO, FEEREMAIN, FEESALE, SALEDIS, SALERETDIS, C_CUSRANK_ID, ",
        "C_CUSTOMERUP_ID, FIRSALEDIS, FEELSALE, FEELTAKE, ISPERIOD, AREAMNG_ID, C_CITY_ID, ",
        "ISAUTOIN, ORDERRATE, RET_RATE, BIGAREAMNG_ID, ISGROUP, ISACCOUNT, C_DEPARTMENT_ID, ",
        "C_CLASSCODE_ID, CODE, C_AREA_ID, PRIORITY, M_DIMCUS1_ID, M_DIMCUS2_ID, M_DIMCUS3_ID, ",
        "M_DIMCUS4_ID, M_DIMCUS5_ID, M_DIMCUS6_ID, M_DIMCUS7_ID, M_DIMCUS8_ID, M_DIMCUS9_ID, ",
        "M_DIMCUS10_ID, BUTSALEDIS, AGTSALEDIS, FIRSALERETDIS, AGTSALERETDIS, TRANDIS, ",
        "C_CUSATTRIB1_ID, C_CUSATTRIB2_ID, C_CUSATTRIB3_ID, C_CUSATTRIB4_ID, C_CUSATTRIB5_ID, ",
        "C_CUSATTRIB6_ID, C_CUSATTRIB7_ID, C_CUSATTRIB8_ID, C_CUSATTRIB9_ID, C_CUSATTRIB10_ID, ",
        "C_CUSATTRIB11_ID, C_CUSATTRIB12_ID, C_CUSATTRIB13_ID, C_CUSATTRIB14_ID, C_CUSATTRIB15_ID, ",
        "C_CUSATTRIB16_ID, C_CUSATTRIB17_ID, C_CUSATTRIB18_ID, C_CUSATTRIB19_ID, C_CUSATTRIB20_ID, ",
        "CAN_BUTSALE, CAN_NOTBUTSALE, CAN_AGTSALE, ISCREFUND, C_CUSTYPE_ID, M_DIM1_ID, ",
        "MOBILE, CALCULATION, ISKD, LEGAL_ID, FIRRETRATE, RETRATE, AGTRETRATE, GL_COMPANY, ",
        "PROFITCENTER, ISTHIRD, LEGAL, IS_PCK, IS_SALE_PCK, IS_RETPUT_PCK, IMGURL1, IMGURL2, ",
        "IMGURL3, IMGURL4, IMGURL5, B_CUSCODE_FORMAT_ID, SALEINVITEM, C_FRANCHISEE_ID, ",
        "C_CUSGROUP_ID, BANK, C_CURRENCY_ID, PAYWAY, TRADEWAY, BIRTHDAY, FRANCHISEE_RELASHIP, ",
        "OPENSTORE_TYPE, STOPDATE, C_BRANCH_ID, C_SALER_ID, SALESREP_ID",
        "from C_CUSTOMER",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC, id=true),
        @Result(column="AD_CLIENT_ID", property="adClientId", jdbcType=JdbcType.NUMERIC),
        @Result(column="AD_ORG_ID", property="adOrgId", jdbcType=JdbcType.NUMERIC),
        @Result(column="MODIFIERID", property="modifierid", jdbcType=JdbcType.NUMERIC),
        @Result(column="CREATIONDATE", property="creationdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFIEDDATE", property="modifieddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="OWNERID", property="ownerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISACTIVE", property="isactive", jdbcType=JdbcType.CHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="ENTERDATE", property="enterdate", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISSTOP", property="isstop", jdbcType=JdbcType.CHAR),
        @Result(column="CONTACTER", property="contacter", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHONE", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADDRESS", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST", property="post", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCOUNT", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="TAXNO", property="taxno", jdbcType=JdbcType.VARCHAR),
        @Result(column="FEEREMAIN", property="feeremain", jdbcType=JdbcType.NUMERIC),
        @Result(column="FEESALE", property="feesale", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALEDIS", property="saledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALERETDIS", property="saleretdis", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSRANK_ID", property="cCusrankId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSTOMERUP_ID", property="cCustomerupId", jdbcType=JdbcType.NUMERIC),
        @Result(column="FIRSALEDIS", property="firsaledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="FEELSALE", property="feelsale", jdbcType=JdbcType.NUMERIC),
        @Result(column="FEELTAKE", property="feeltake", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISPERIOD", property="isperiod", jdbcType=JdbcType.CHAR),
        @Result(column="AREAMNG_ID", property="areamngId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CITY_ID", property="cCityId", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISAUTOIN", property="isautoin", jdbcType=JdbcType.CHAR),
        @Result(column="ORDERRATE", property="orderrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="RET_RATE", property="retRate", jdbcType=JdbcType.NUMERIC),
        @Result(column="BIGAREAMNG_ID", property="bigareamngId", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISGROUP", property="isgroup", jdbcType=JdbcType.CHAR),
        @Result(column="ISACCOUNT", property="isaccount", jdbcType=JdbcType.CHAR),
        @Result(column="C_DEPARTMENT_ID", property="cDepartmentId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CLASSCODE_ID", property="cClasscodeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_AREA_ID", property="cAreaId", jdbcType=JdbcType.NUMERIC),
        @Result(column="PRIORITY", property="priority", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS1_ID", property="mDimcus1Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS2_ID", property="mDimcus2Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS3_ID", property="mDimcus3Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS4_ID", property="mDimcus4Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS5_ID", property="mDimcus5Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS6_ID", property="mDimcus6Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS7_ID", property="mDimcus7Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS8_ID", property="mDimcus8Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS9_ID", property="mDimcus9Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIMCUS10_ID", property="mDimcus10Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="BUTSALEDIS", property="butsaledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="AGTSALEDIS", property="agtsaledis", jdbcType=JdbcType.NUMERIC),
        @Result(column="FIRSALERETDIS", property="firsaleretdis", jdbcType=JdbcType.NUMERIC),
        @Result(column="AGTSALERETDIS", property="agtsaleretdis", jdbcType=JdbcType.NUMERIC),
        @Result(column="TRANDIS", property="trandis", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB1_ID", property="cCusattrib1Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB2_ID", property="cCusattrib2Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB3_ID", property="cCusattrib3Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB4_ID", property="cCusattrib4Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB5_ID", property="cCusattrib5Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB6_ID", property="cCusattrib6Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB7_ID", property="cCusattrib7Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB8_ID", property="cCusattrib8Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB9_ID", property="cCusattrib9Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB10_ID", property="cCusattrib10Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB11_ID", property="cCusattrib11Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB12_ID", property="cCusattrib12Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB13_ID", property="cCusattrib13Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB14_ID", property="cCusattrib14Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB15_ID", property="cCusattrib15Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB16_ID", property="cCusattrib16Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB17_ID", property="cCusattrib17Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB18_ID", property="cCusattrib18Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB19_ID", property="cCusattrib19Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSATTRIB20_ID", property="cCusattrib20Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="CAN_BUTSALE", property="canButsale", jdbcType=JdbcType.CHAR),
        @Result(column="CAN_NOTBUTSALE", property="canNotbutsale", jdbcType=JdbcType.CHAR),
        @Result(column="CAN_AGTSALE", property="canAgtsale", jdbcType=JdbcType.CHAR),
        @Result(column="ISCREFUND", property="iscrefund", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_CUSTYPE_ID", property="cCustypeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_DIM1_ID", property="mDim1Id", jdbcType=JdbcType.NUMERIC),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="CALCULATION", property="calculation", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISKD", property="iskd", jdbcType=JdbcType.CHAR),
        @Result(column="LEGAL_ID", property="legalId", jdbcType=JdbcType.NUMERIC),
        @Result(column="FIRRETRATE", property="firretrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="RETRATE", property="retrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="AGTRETRATE", property="agtretrate", jdbcType=JdbcType.NUMERIC),
        @Result(column="GL_COMPANY", property="glCompany", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROFITCENTER", property="profitcenter", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISTHIRD", property="isthird", jdbcType=JdbcType.CHAR),
        @Result(column="LEGAL", property="legal", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_PCK", property="isPck", jdbcType=JdbcType.CHAR),
        @Result(column="IS_SALE_PCK", property="isSalePck", jdbcType=JdbcType.CHAR),
        @Result(column="IS_RETPUT_PCK", property="isRetputPck", jdbcType=JdbcType.CHAR),
        @Result(column="IMGURL1", property="imgurl1", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL2", property="imgurl2", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL3", property="imgurl3", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL4", property="imgurl4", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMGURL5", property="imgurl5", jdbcType=JdbcType.VARCHAR),
        @Result(column="B_CUSCODE_FORMAT_ID", property="bCuscodeFormatId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALEINVITEM", property="saleinvitem", jdbcType=JdbcType.CHAR),
        @Result(column="C_FRANCHISEE_ID", property="cFranchiseeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSGROUP_ID", property="cCusgroupId", jdbcType=JdbcType.NUMERIC),
        @Result(column="BANK", property="bank", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_CURRENCY_ID", property="cCurrencyId", jdbcType=JdbcType.NUMERIC),
        @Result(column="PAYWAY", property="payway", jdbcType=JdbcType.CHAR),
        @Result(column="TRADEWAY", property="tradeway", jdbcType=JdbcType.CHAR),
        @Result(column="BIRTHDAY", property="birthday", jdbcType=JdbcType.NUMERIC),
        @Result(column="FRANCHISEE_RELASHIP", property="franchiseeRelaship", jdbcType=JdbcType.CHAR),
        @Result(column="OPENSTORE_TYPE", property="openstoreType", jdbcType=JdbcType.CHAR),
        @Result(column="STOPDATE", property="stopdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="C_BRANCH_ID", property="cBranchId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_SALER_ID", property="cSalerId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SALESREP_ID", property="salesrepId", jdbcType=JdbcType.NUMERIC)
    })
    Customer selectByPrimaryKey(Long id);

    @UpdateProvider(type=CustomerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    @UpdateProvider(type=CustomerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    @UpdateProvider(type=CustomerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Customer record);

    @Update({
        "update C_CUSTOMER",
        "set AD_CLIENT_ID = #{adClientId,jdbcType=NUMERIC},",
          "AD_ORG_ID = #{adOrgId,jdbcType=NUMERIC},",
          "MODIFIERID = #{modifierid,jdbcType=NUMERIC},",
          "CREATIONDATE = #{creationdate,jdbcType=TIMESTAMP},",
          "MODIFIEDDATE = #{modifieddate,jdbcType=TIMESTAMP},",
          "OWNERID = #{ownerid,jdbcType=NUMERIC},",
          "ISACTIVE = #{isactive,jdbcType=CHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "DESCRIPTION = #{description,jdbcType=VARCHAR},",
          "ENTERDATE = #{enterdate,jdbcType=NUMERIC},",
          "ISSTOP = #{isstop,jdbcType=CHAR},",
          "CONTACTER = #{contacter,jdbcType=VARCHAR},",
          "PHONE = #{phone,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "POST = #{post,jdbcType=VARCHAR},",
          "ACCOUNT = #{account,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "TAXNO = #{taxno,jdbcType=VARCHAR},",
          "FEEREMAIN = #{feeremain,jdbcType=NUMERIC},",
          "FEESALE = #{feesale,jdbcType=NUMERIC},",
          "SALEDIS = #{saledis,jdbcType=NUMERIC},",
          "SALERETDIS = #{saleretdis,jdbcType=NUMERIC},",
          "C_CUSRANK_ID = #{cCusrankId,jdbcType=NUMERIC},",
          "C_CUSTOMERUP_ID = #{cCustomerupId,jdbcType=NUMERIC},",
          "FIRSALEDIS = #{firsaledis,jdbcType=NUMERIC},",
          "FEELSALE = #{feelsale,jdbcType=NUMERIC},",
          "FEELTAKE = #{feeltake,jdbcType=NUMERIC},",
          "ISPERIOD = #{isperiod,jdbcType=CHAR},",
          "AREAMNG_ID = #{areamngId,jdbcType=NUMERIC},",
          "C_CITY_ID = #{cCityId,jdbcType=NUMERIC},",
          "ISAUTOIN = #{isautoin,jdbcType=CHAR},",
          "ORDERRATE = #{orderrate,jdbcType=NUMERIC},",
          "RET_RATE = #{retRate,jdbcType=NUMERIC},",
          "BIGAREAMNG_ID = #{bigareamngId,jdbcType=NUMERIC},",
          "ISGROUP = #{isgroup,jdbcType=CHAR},",
          "ISACCOUNT = #{isaccount,jdbcType=CHAR},",
          "C_DEPARTMENT_ID = #{cDepartmentId,jdbcType=NUMERIC},",
          "C_CLASSCODE_ID = #{cClasscodeId,jdbcType=NUMERIC},",
          "CODE = #{code,jdbcType=VARCHAR},",
          "C_AREA_ID = #{cAreaId,jdbcType=NUMERIC},",
          "PRIORITY = #{priority,jdbcType=NUMERIC},",
          "M_DIMCUS1_ID = #{mDimcus1Id,jdbcType=NUMERIC},",
          "M_DIMCUS2_ID = #{mDimcus2Id,jdbcType=NUMERIC},",
          "M_DIMCUS3_ID = #{mDimcus3Id,jdbcType=NUMERIC},",
          "M_DIMCUS4_ID = #{mDimcus4Id,jdbcType=NUMERIC},",
          "M_DIMCUS5_ID = #{mDimcus5Id,jdbcType=NUMERIC},",
          "M_DIMCUS6_ID = #{mDimcus6Id,jdbcType=NUMERIC},",
          "M_DIMCUS7_ID = #{mDimcus7Id,jdbcType=NUMERIC},",
          "M_DIMCUS8_ID = #{mDimcus8Id,jdbcType=NUMERIC},",
          "M_DIMCUS9_ID = #{mDimcus9Id,jdbcType=NUMERIC},",
          "M_DIMCUS10_ID = #{mDimcus10Id,jdbcType=NUMERIC},",
          "BUTSALEDIS = #{butsaledis,jdbcType=NUMERIC},",
          "AGTSALEDIS = #{agtsaledis,jdbcType=NUMERIC},",
          "FIRSALERETDIS = #{firsaleretdis,jdbcType=NUMERIC},",
          "AGTSALERETDIS = #{agtsaleretdis,jdbcType=NUMERIC},",
          "TRANDIS = #{trandis,jdbcType=NUMERIC},",
          "C_CUSATTRIB1_ID = #{cCusattrib1Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB2_ID = #{cCusattrib2Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB3_ID = #{cCusattrib3Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB4_ID = #{cCusattrib4Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB5_ID = #{cCusattrib5Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB6_ID = #{cCusattrib6Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB7_ID = #{cCusattrib7Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB8_ID = #{cCusattrib8Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB9_ID = #{cCusattrib9Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB10_ID = #{cCusattrib10Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB11_ID = #{cCusattrib11Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB12_ID = #{cCusattrib12Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB13_ID = #{cCusattrib13Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB14_ID = #{cCusattrib14Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB15_ID = #{cCusattrib15Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB16_ID = #{cCusattrib16Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB17_ID = #{cCusattrib17Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB18_ID = #{cCusattrib18Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB19_ID = #{cCusattrib19Id,jdbcType=NUMERIC},",
          "C_CUSATTRIB20_ID = #{cCusattrib20Id,jdbcType=NUMERIC},",
          "CAN_BUTSALE = #{canButsale,jdbcType=CHAR},",
          "CAN_NOTBUTSALE = #{canNotbutsale,jdbcType=CHAR},",
          "CAN_AGTSALE = #{canAgtsale,jdbcType=CHAR},",
          "ISCREFUND = #{iscrefund,jdbcType=VARCHAR},",
          "C_CUSTYPE_ID = #{cCustypeId,jdbcType=NUMERIC},",
          "M_DIM1_ID = #{mDim1Id,jdbcType=NUMERIC},",
          "MOBILE = #{mobile,jdbcType=VARCHAR},",
          "CALCULATION = #{calculation,jdbcType=NUMERIC},",
          "ISKD = #{iskd,jdbcType=CHAR},",
          "LEGAL_ID = #{legalId,jdbcType=NUMERIC},",
          "FIRRETRATE = #{firretrate,jdbcType=NUMERIC},",
          "RETRATE = #{retrate,jdbcType=NUMERIC},",
          "AGTRETRATE = #{agtretrate,jdbcType=NUMERIC},",
          "GL_COMPANY = #{glCompany,jdbcType=VARCHAR},",
          "PROFITCENTER = #{profitcenter,jdbcType=VARCHAR},",
          "ISTHIRD = #{isthird,jdbcType=CHAR},",
          "LEGAL = #{legal,jdbcType=VARCHAR},",
          "IS_PCK = #{isPck,jdbcType=CHAR},",
          "IS_SALE_PCK = #{isSalePck,jdbcType=CHAR},",
          "IS_RETPUT_PCK = #{isRetputPck,jdbcType=CHAR},",
          "IMGURL1 = #{imgurl1,jdbcType=VARCHAR},",
          "IMGURL2 = #{imgurl2,jdbcType=VARCHAR},",
          "IMGURL3 = #{imgurl3,jdbcType=VARCHAR},",
          "IMGURL4 = #{imgurl4,jdbcType=VARCHAR},",
          "IMGURL5 = #{imgurl5,jdbcType=VARCHAR},",
          "B_CUSCODE_FORMAT_ID = #{bCuscodeFormatId,jdbcType=NUMERIC},",
          "SALEINVITEM = #{saleinvitem,jdbcType=CHAR},",
          "C_FRANCHISEE_ID = #{cFranchiseeId,jdbcType=NUMERIC},",
          "C_CUSGROUP_ID = #{cCusgroupId,jdbcType=NUMERIC},",
          "BANK = #{bank,jdbcType=VARCHAR},",
          "C_CURRENCY_ID = #{cCurrencyId,jdbcType=NUMERIC},",
          "PAYWAY = #{payway,jdbcType=CHAR},",
          "TRADEWAY = #{tradeway,jdbcType=CHAR},",
          "BIRTHDAY = #{birthday,jdbcType=NUMERIC},",
          "FRANCHISEE_RELASHIP = #{franchiseeRelaship,jdbcType=CHAR},",
          "OPENSTORE_TYPE = #{openstoreType,jdbcType=CHAR},",
          "STOPDATE = #{stopdate,jdbcType=TIMESTAMP},",
          "C_BRANCH_ID = #{cBranchId,jdbcType=NUMERIC},",
          "C_SALER_ID = #{cSalerId,jdbcType=NUMERIC},",
          "SALESREP_ID = #{salesrepId,jdbcType=NUMERIC}",
        "where ID = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Customer record);
}