package com.cros.vue.mapper;

import com.cros.vue.entity.RefundAudit;
import com.cros.vue.entity.RefundAuditExample;
import java.util.List;

import com.cros.vue.entity.RefundAuditItem;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface RefundAuditMapper {
    @SelectProvider(type=RefundAuditSqlProvider.class, method="countByExample")
    long countByExample(RefundAuditExample example);

    @DeleteProvider(type=RefundAuditSqlProvider.class, method="deleteByExample")
    int deleteByExample(RefundAuditExample example);

    @Insert({
        "insert into M_RET_SALECONF (ID, AD_CLIENT_ID, ",
        "AD_ORG_ID, OWNERID, ",
        "MODIFIERID, CREATIONDATE, ",
        "MODIFIEDDATE, ISACTIVE, ",
        "DOCNO, DOCTYPE, BILLDATE, ",
        "SALESREP_ID, C_STORE_ID, ",
        "C_CUSTOMER_ID, DESCRIPTION, ",
        "AU_STATE, AU_PI_ID, AVG_DISCOUNT, ",
        "TOT_LINES, TOT_QTY, ",
        "TOT_AMT_LIST, TOT_AMT_ACTUAL, ",
        "C_PERIOD_ID, C_ORIG_ID, ",
        "OUT_STATUS, IN_STATUS, ",
        "TOT_QTYOUT, TOT_AMTOUT_LIST, ",
        "TOT_AMTOUT_ACTUAL, TOT_QTYIN, ",
        "TOT_AMTIN_LIST, TOT_AMTIN_ACTUAL, ",
        "DIFFREASON, DATEOUT, ",
        "DATEIN, C_CUSTOMERUP_ID, ",
        "RETSALETYPE, RETSALETYPE1, ",
        "STATUSERID, STATUSTIME, ",
        "INERID, INTIME, ",
        "OUTERID, OUTTIME, ",
        "C_RET_SALETYPE_ID, BOX_STATUS, ",
        "C_TRANWAY_JZ_ID, TRANWAYNO, ",
        "TRANWAY_PAY, OPERATOERID, ",
        "OPER_STATUS, PICKERID, ",
        "ISUF, PROCESS_MODE, ",
        "TOT_AMT_PRECOST, TOT_AMTIN_PRECOST, ",
        "DISCOUNT, ISBOX, ",
        "C_SALEDISTYPE_ID, IMAGEURL, ",
        "C_CARGOTYPE_ID, C_STORE_LOCATION_ID, ",
        "PRINTTIMES, PRINTOUTTIMES, ",
        "PRINTINTIMES, C_CARGOINTYPE_ID, ",
        "SCANSTATE, SENDQTY, ",
        "SUBSENDQTY, REALDATE, ",
        "IFMOVE, OUT_AU_STATE, OUT_AU_PI_ID, ",
        "IN_AU_STATE, IN_AU_PI_ID, ",
        "TOT_AMT_PRICE, AMT_DEDUCTION, ",
        "PCK_STATUS, PCHECKID, ",
        "PCHECKTIME, TOT_AMTINVED, ",
        "TOT_QTYINVED, M_CRORETSALE_ID, ",
        "IS_MAIN_RETSALE, IS_CRORETSALEIN, ",
        "CARRIER, SHIPPING_REMARK, ",
        "IS_TOWMS, DEST_ADDR, ",
        "M_BOX_ID, QTY_BOX, ",
        "TOT_TAX_AMT, TOT_NOTAX_AMT, ",
        "TAX_DIS, PAYMENTSTYLE, ",
        "SCAN_STATUS, BILLKIND, ",
        "CONTRACTNO_FILE, CONFIRM_STATUS, ",
        "CONFIRM_STATUSTIME, CONFIRM_STATUSERID, ",
        "BILLNO, FISNO, BYIN_STATUS, ",
        "SCANNERID, C_SALER_ID, ",
        "SCAN_INTIME, CONFIRM_INTIME, ",
        "DELIVERY_CONFIRMTIME, BYOUT_STATUS, ",
        "UNPICK_STORE_ID, SCANIN_STATUS, ",
        "BEHALF_REMARK, ISDEFAULTSCAN, ",
        "STATUS, RETINFO, ",
        "SALE_TYPE)",
        "values (#{id,jdbcType=NUMERIC}, #{adClientId,jdbcType=NUMERIC}, ",
        "#{adOrgId,jdbcType=NUMERIC}, #{ownerid,jdbcType=NUMERIC}, ",
        "#{modifierid,jdbcType=NUMERIC}, #{creationdate,jdbcType=TIMESTAMP}, ",
        "#{modifieddate,jdbcType=TIMESTAMP}, #{isactive,jdbcType=CHAR}, ",
        "#{docno,jdbcType=VARCHAR}, #{doctype,jdbcType=CHAR}, #{billdate,jdbcType=NUMERIC}, ",
        "#{salesrepId,jdbcType=NUMERIC}, #{cStoreId,jdbcType=NUMERIC}, ",
        "#{cCustomerId,jdbcType=NUMERIC}, #{description,jdbcType=VARCHAR}, ",
        "#{auState,jdbcType=CHAR}, #{auPiId,jdbcType=NUMERIC}, #{avgDiscount,jdbcType=NUMERIC}, ",
        "#{totLines,jdbcType=NUMERIC}, #{totQty,jdbcType=NUMERIC}, ",
        "#{totAmtList,jdbcType=NUMERIC}, #{totAmtActual,jdbcType=NUMERIC}, ",
        "#{cPeriodId,jdbcType=NUMERIC}, #{cOrigId,jdbcType=NUMERIC}, ",
        "#{outStatus,jdbcType=NUMERIC}, #{inStatus,jdbcType=NUMERIC}, ",
        "#{totQtyout,jdbcType=NUMERIC}, #{totAmtoutList,jdbcType=NUMERIC}, ",
        "#{totAmtoutActual,jdbcType=NUMERIC}, #{totQtyin,jdbcType=NUMERIC}, ",
        "#{totAmtinList,jdbcType=NUMERIC}, #{totAmtinActual,jdbcType=NUMERIC}, ",
        "#{diffreason,jdbcType=VARCHAR}, #{dateout,jdbcType=NUMERIC}, ",
        "#{datein,jdbcType=NUMERIC}, #{cCustomerupId,jdbcType=NUMERIC}, ",
        "#{retsaletype,jdbcType=CHAR}, #{retsaletype1,jdbcType=CHAR}, ",
        "#{statuserid,jdbcType=NUMERIC}, #{statustime,jdbcType=TIMESTAMP}, ",
        "#{inerid,jdbcType=NUMERIC}, #{intime,jdbcType=TIMESTAMP}, ",
        "#{outerid,jdbcType=NUMERIC}, #{outtime,jdbcType=TIMESTAMP}, ",
        "#{cRetSaletypeId,jdbcType=NUMERIC}, #{boxStatus,jdbcType=NUMERIC}, ",
        "#{cTranwayJzId,jdbcType=NUMERIC}, #{tranwayno,jdbcType=VARCHAR}, ",
        "#{tranwayPay,jdbcType=NUMERIC}, #{operatoerid,jdbcType=NUMERIC}, ",
        "#{operStatus,jdbcType=VARCHAR}, #{pickerid,jdbcType=NUMERIC}, ",
        "#{isuf,jdbcType=CHAR}, #{processMode,jdbcType=NUMERIC}, ",
        "#{totAmtPrecost,jdbcType=NUMERIC}, #{totAmtinPrecost,jdbcType=NUMERIC}, ",
        "#{discount,jdbcType=NUMERIC}, #{isbox,jdbcType=NUMERIC}, ",
        "#{cSaledistypeId,jdbcType=NUMERIC}, #{imageurl,jdbcType=VARCHAR}, ",
        "#{cCargotypeId,jdbcType=NUMERIC}, #{cStoreLocationId,jdbcType=NUMERIC}, ",
        "#{printtimes,jdbcType=NUMERIC}, #{printouttimes,jdbcType=NUMERIC}, ",
        "#{printintimes,jdbcType=NUMERIC}, #{cCargointypeId,jdbcType=NUMERIC}, ",
        "#{scanstate,jdbcType=CHAR}, #{sendqty,jdbcType=NUMERIC}, ",
        "#{subsendqty,jdbcType=NUMERIC}, #{realdate,jdbcType=NUMERIC}, ",
        "#{ifmove,jdbcType=CHAR}, #{outAuState,jdbcType=CHAR}, #{outAuPiId,jdbcType=NUMERIC}, ",
        "#{inAuState,jdbcType=CHAR}, #{inAuPiId,jdbcType=NUMERIC}, ",
        "#{totAmtPrice,jdbcType=NUMERIC}, #{amtDeduction,jdbcType=NUMERIC}, ",
        "#{pckStatus,jdbcType=NUMERIC}, #{pcheckid,jdbcType=NUMERIC}, ",
        "#{pchecktime,jdbcType=TIMESTAMP}, #{totAmtinved,jdbcType=NUMERIC}, ",
        "#{totQtyinved,jdbcType=NUMERIC}, #{mCroretsaleId,jdbcType=NUMERIC}, ",
        "#{isMainRetsale,jdbcType=CHAR}, #{isCroretsalein,jdbcType=CHAR}, ",
        "#{carrier,jdbcType=VARCHAR}, #{shippingRemark,jdbcType=VARCHAR}, ",
        "#{isTowms,jdbcType=CHAR}, #{destAddr,jdbcType=VARCHAR}, ",
        "#{mBoxId,jdbcType=NUMERIC}, #{qtyBox,jdbcType=NUMERIC}, ",
        "#{totTaxAmt,jdbcType=NUMERIC}, #{totNotaxAmt,jdbcType=NUMERIC}, ",
        "#{taxDis,jdbcType=NUMERIC}, #{paymentstyle,jdbcType=CHAR}, ",
        "#{scanStatus,jdbcType=NUMERIC}, #{billkind,jdbcType=NUMERIC}, ",
        "#{contractnoFile,jdbcType=VARCHAR}, #{confirmStatus,jdbcType=NUMERIC}, ",
        "#{confirmStatustime,jdbcType=TIMESTAMP}, #{confirmStatuserid,jdbcType=NUMERIC}, ",
        "#{billno,jdbcType=VARCHAR}, #{fisno,jdbcType=VARCHAR}, #{byinStatus,jdbcType=NUMERIC}, ",
        "#{scannerid,jdbcType=NUMERIC}, #{cSalerId,jdbcType=NUMERIC}, ",
        "#{scanIntime,jdbcType=TIMESTAMP}, #{confirmIntime,jdbcType=TIMESTAMP}, ",
        "#{deliveryConfirmtime,jdbcType=TIMESTAMP}, #{byoutStatus,jdbcType=NUMERIC}, ",
        "#{unpickStoreId,jdbcType=NUMERIC}, #{scaninStatus,jdbcType=NUMERIC}, ",
        "#{behalfRemark,jdbcType=VARCHAR}, #{isdefaultscan,jdbcType=CHAR}, ",
        "#{status,jdbcType=NUMERIC}, #{retinfo,jdbcType=VARCHAR}, ",
        "#{saleType,jdbcType=NUMERIC})"
    })
    int insert(RefundAudit record);

    @InsertProvider(type=RefundAuditSqlProvider.class, method="insertSelective")
    int insertSelective(RefundAudit record);

    @Select({
            "select",
            "t1.id,t1.AD_CLIENT_ID,t1.AD_ORG_ID,t1.OWNERID,t1.MODIFIERID,t1.CREATIONDATE,",
            "t1.MODIFIEDDATE,t1.ISACTIVE,t1.DOCNO,t1.DOCTYPE,to_date(t1.BILLDATE,'YYYY-MM-DD'),",
            "t1.SALESREP_ID,t1.C_STORE_ID,t1.C_CUSTOMER_ID,t1.DESCRIPTION,t1.AU_STATE,t1.AU_PI_ID,",
            "t1.AVG_DISCOUNT,t1.TOT_LINES,t1.TOT_QTY,t1.TOT_AMT_LIST,t1.TOT_AMT_ACTUAL,t1.C_PERIOD_ID,",
            "t1.C_ORIG_ID,t1.OUT_STATUS,t1.IN_STATUS,t1.TOT_QTYOUT,t1.TOT_AMTOUT_LIST,t1.TOT_AMTOUT_ACTUAL,",
            "t1.TOT_QTYIN,t1.TOT_AMTIN_LIST,t1.TOT_AMTIN_ACTUAL,t1.DIFFREASON,t1.DATEOUT,t1.DATEIN,",
            "t1.C_CUSTOMERUP_ID,t1.RETSALETYPE,t8.description retsaleName,t1.RETSALETYPE1,t1.STATUSERID,",
            "t1.STATUSTIME,t1.INERID,t1.INTIME,t1.OUTERID,t1.OUTTIME,t1.C_RET_SALETYPE_ID,t1.BOX_STATUS,",
            "t1.C_TRANWAY_JZ_ID,t1.TRANWAYNO,t1.TRANWAY_PAY,t1.OPERATOERID,t1.OPER_STATUS,",
            "t1.PICKERID,t1.ISUF,t1.PROCESS_MODE,t1.TOT_AMT_PRECOST,t1.TOT_AMTIN_PRECOST,t1.DISCOUNT,",
            "t1.ISBOX,t1.C_SALEDISTYPE_ID,t1.IMAGEURL,t1.C_CARGOTYPE_ID,t1.C_STORE_LOCATION_ID,t1.PRINTTIMES,",
            "t1.PRINTOUTTIMES,t1.PRINTINTIMES,t1.C_CARGOINTYPE_ID,t1.SCANSTATE,t1.SENDQTY,t1.SUBSENDQTY,",
            "t1.REALDATE,t1.IFMOVE,t1.OUT_AU_STATE,t1.OUT_AU_PI_ID,t1.IN_AU_STATE,t1.IN_AU_PI_ID,t1.TOT_AMT_PRICE,t1.AMT_DEDUCTION,t1.PCK_STATUS,",
            "t1.PCHECKID,t1.PCHECKTIME,t1.TOT_AMTINVED,t1.TOT_QTYINVED,t1.M_CRORETSALE_ID,t1.IS_MAIN_RETSALE,t1.IS_CRORETSALEIN,t1.CARRIER,t1.SHIPPING_REMARK,",
            "t1.IS_TOWMS,t1.DEST_ADDR,t1.M_BOX_ID,t1.QTY_BOX,t1.TOT_TAX_AMT,t1.TOT_NOTAX_AMT,t1.TAX_DIS,t1.PAYMENTSTYLE,t1.SCAN_STATUS,t1.BILLKIND,t9.description billName,",
            "t1.CONTRACTNO_FILE,t1.CONFIRM_STATUS,t1.CONFIRM_STATUSTIME,t1.CONFIRM_STATUSERID,t1.BILLNO,t1.FISNO,t1.BYIN_STATUS,t1.SCANNERID,t1.C_SALER_ID,t1.SCAN_INTIME,",
            "t1.CONFIRM_INTIME,t1.DELIVERY_CONFIRMTIME,t1.BYOUT_STATUS,t1.UNPICK_STORE_ID,t1.SCANIN_STATUS,t1.BEHALF_REMARK,t1.ISDEFAULTSCAN,t1.STATUS,t6.description statusName,t1.RETINFO,t1.SALE_TYPE,t2.name storeName,t2.code storeCode,t3.name blockName,t3.code blockCode,t4.code lcCode,t4.name lcName,t4.description lcDescription,t5.code custCode,t5.name custName,t5.description custDescription",
            "from M_RET_SALECONF t1 inner join C_STORE t2  on t1.C_STORE_ID=t2.id ",
            "left join  C_BLOCK t3 on t2.C_BLOCK_ID=t3.id ",
            "inner join C_STORE t4 on t1.C_ORIG_ID=t4.id ",
            "inner join C_CUSTOMER t5 on t1.C_CUSTOMER_ID=t5.id ",
            "left join AD_LIMITVALUE t6 on t1.STATUS=t6.value and t6.ad_limitvalue_group_id=1609 ",
            "left join AD_LIMITVALUE t7 on t1.SALE_TYPE=t7.value and t7.ad_limitvalue_group_id=1728 ",
            "left join AD_LIMITVALUE t8 on trim(t1.RETSALETYPE)=t8.value and t8.ad_limitvalue_group_id=1529 ",
            "left join AD_LIMITVALUE t9 on t1.BILLKIND=t9.value and t9.ad_limitvalue_group_id=1522",
            "where t1.id = #{id,jdbcType=NUMERIC}"
    })
    @Results({
            @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC),
            @Result(column="AD_CLIENT_ID", property="adClientId", jdbcType=JdbcType.NUMERIC),
            @Result(column="AD_ORG_ID", property="adOrgId", jdbcType=JdbcType.NUMERIC),
            @Result(column="OWNERID", property="ownerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="MODIFIERID", property="modifierid", jdbcType=JdbcType.NUMERIC),
            @Result(column="CREATIONDATE", property="creationdate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="MODIFIEDDATE", property="modifieddate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="ISACTIVE", property="isactive", jdbcType=JdbcType.CHAR),
            @Result(column="DOCNO", property="docno", jdbcType=JdbcType.VARCHAR),
            @Result(column="DOCTYPE", property="doctype", jdbcType=JdbcType.CHAR),
            @Result(column="BILLDATE", property="billdate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="SALESREP_ID", property="salesrepId", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_STORE_ID", property="cStoreId", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_CUSTOMER_ID", property="cCustomerId", jdbcType=JdbcType.NUMERIC),
            @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
            @Result(column="AU_STATE", property="auState", jdbcType=JdbcType.CHAR),
            @Result(column="AU_PI_ID", property="auPiId", jdbcType=JdbcType.NUMERIC),
            @Result(column="AVG_DISCOUNT", property="avgDiscount", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_LINES", property="totLines", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_QTY", property="totQty", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMT_LIST", property="totAmtList", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMT_ACTUAL", property="totAmtActual", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_PERIOD_ID", property="cPeriodId", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_ORIG_ID", property="cOrigId", jdbcType=JdbcType.NUMERIC),
            @Result(column="OUT_STATUS", property="outStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="IN_STATUS", property="inStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_QTYOUT", property="totQtyout", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMTOUT_LIST", property="totAmtoutList", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMTOUT_ACTUAL", property="totAmtoutActual", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_QTYIN", property="totQtyin", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMTIN_LIST", property="totAmtinList", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMTIN_ACTUAL", property="totAmtinActual", jdbcType=JdbcType.NUMERIC),
            @Result(column="DIFFREASON", property="diffreason", jdbcType=JdbcType.VARCHAR),
            @Result(column="DATEOUT", property="dateout", jdbcType=JdbcType.NUMERIC),
            @Result(column="DATEIN", property="datein", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_CUSTOMERUP_ID", property="cCustomerupId", jdbcType=JdbcType.NUMERIC),
            @Result(column="RETSALETYPE", property="retsaletype", jdbcType=JdbcType.CHAR),
            @Result(column="RETSALETYPE1", property="retsaletype1", jdbcType=JdbcType.CHAR),
            @Result(column="STATUSERID", property="statuserid", jdbcType=JdbcType.NUMERIC),
            @Result(column="STATUSTIME", property="statustime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="INERID", property="inerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="INTIME", property="intime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="OUTERID", property="outerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="OUTTIME", property="outtime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="C_RET_SALETYPE_ID", property="cRetSaletypeId", jdbcType=JdbcType.NUMERIC),
            @Result(column="BOX_STATUS", property="boxStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_TRANWAY_JZ_ID", property="cTranwayJzId", jdbcType=JdbcType.NUMERIC),
            @Result(column="TRANWAYNO", property="tranwayno", jdbcType=JdbcType.VARCHAR),
            @Result(column="TRANWAY_PAY", property="tranwayPay", jdbcType=JdbcType.NUMERIC),
            @Result(column="OPERATOERID", property="operatoerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="OPER_STATUS", property="operStatus", jdbcType=JdbcType.VARCHAR),
            @Result(column="PICKERID", property="pickerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="ISUF", property="isuf", jdbcType=JdbcType.CHAR),
            @Result(column="PROCESS_MODE", property="processMode", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMT_PRECOST", property="totAmtPrecost", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMTIN_PRECOST", property="totAmtinPrecost", jdbcType=JdbcType.NUMERIC),
            @Result(column="DISCOUNT", property="discount", jdbcType=JdbcType.NUMERIC),
            @Result(column="ISBOX", property="isbox", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_SALEDISTYPE_ID", property="cSaledistypeId", jdbcType=JdbcType.NUMERIC),
            @Result(column="IMAGEURL", property="imageurl", jdbcType=JdbcType.VARCHAR),
            @Result(column="C_CARGOTYPE_ID", property="cCargotypeId", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_STORE_LOCATION_ID", property="cStoreLocationId", jdbcType=JdbcType.NUMERIC),
            @Result(column="PRINTTIMES", property="printtimes", jdbcType=JdbcType.NUMERIC),
            @Result(column="PRINTOUTTIMES", property="printouttimes", jdbcType=JdbcType.NUMERIC),
            @Result(column="PRINTINTIMES", property="printintimes", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_CARGOINTYPE_ID", property="cCargointypeId", jdbcType=JdbcType.NUMERIC),
            @Result(column="SCANSTATE", property="scanstate", jdbcType=JdbcType.CHAR),
            @Result(column="SENDQTY", property="sendqty", jdbcType=JdbcType.NUMERIC),
            @Result(column="SUBSENDQTY", property="subsendqty", jdbcType=JdbcType.NUMERIC),
            @Result(column="REALDATE", property="realdate", jdbcType=JdbcType.NUMERIC),
            @Result(column="IFMOVE", property="ifmove", jdbcType=JdbcType.CHAR),
            @Result(column="OUT_AU_STATE", property="outAuState", jdbcType=JdbcType.CHAR),
            @Result(column="OUT_AU_PI_ID", property="outAuPiId", jdbcType=JdbcType.NUMERIC),
            @Result(column="IN_AU_STATE", property="inAuState", jdbcType=JdbcType.CHAR),
            @Result(column="IN_AU_PI_ID", property="inAuPiId", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_AMT_PRICE", property="totAmtPrice", jdbcType=JdbcType.NUMERIC),
            @Result(column="AMT_DEDUCTION", property="amtDeduction", jdbcType=JdbcType.NUMERIC),
            @Result(column="PCK_STATUS", property="pckStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="PCHECKID", property="pcheckid", jdbcType=JdbcType.NUMERIC),
            @Result(column="PCHECKTIME", property="pchecktime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="TOT_AMTINVED", property="totAmtinved", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_QTYINVED", property="totQtyinved", jdbcType=JdbcType.NUMERIC),
            @Result(column="M_CRORETSALE_ID", property="mCroretsaleId", jdbcType=JdbcType.NUMERIC),
            @Result(column="IS_MAIN_RETSALE", property="isMainRetsale", jdbcType=JdbcType.CHAR),
            @Result(column="IS_CRORETSALEIN", property="isCroretsalein", jdbcType=JdbcType.CHAR),
            @Result(column="CARRIER", property="carrier", jdbcType=JdbcType.VARCHAR),
            @Result(column="SHIPPING_REMARK", property="shippingRemark", jdbcType=JdbcType.VARCHAR),
            @Result(column="IS_TOWMS", property="isTowms", jdbcType=JdbcType.CHAR),
            @Result(column="DEST_ADDR", property="destAddr", jdbcType=JdbcType.VARCHAR),
            @Result(column="M_BOX_ID", property="mBoxId", jdbcType=JdbcType.NUMERIC),
            @Result(column="QTY_BOX", property="qtyBox", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_TAX_AMT", property="totTaxAmt", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_NOTAX_AMT", property="totNotaxAmt", jdbcType=JdbcType.NUMERIC),
            @Result(column="TAX_DIS", property="taxDis", jdbcType=JdbcType.NUMERIC),
            @Result(column="PAYMENTSTYLE", property="paymentstyle", jdbcType=JdbcType.CHAR),
            @Result(column="SCAN_STATUS", property="scanStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="BILLKIND", property="billkind", jdbcType=JdbcType.NUMERIC),
            @Result(column="CONTRACTNO_FILE", property="contractnoFile", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONFIRM_STATUS", property="confirmStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="CONFIRM_STATUSTIME", property="confirmStatustime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="CONFIRM_STATUSERID", property="confirmStatuserid", jdbcType=JdbcType.NUMERIC),
            @Result(column="BILLNO", property="billno", jdbcType=JdbcType.VARCHAR),
            @Result(column="FISNO", property="fisno", jdbcType=JdbcType.VARCHAR),
            @Result(column="BYIN_STATUS", property="byinStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="SCANNERID", property="scannerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="C_SALER_ID", property="cSalerId", jdbcType=JdbcType.NUMERIC),
            @Result(column="SCAN_INTIME", property="scanIntime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="CONFIRM_INTIME", property="confirmIntime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="DELIVERY_CONFIRMTIME", property="deliveryConfirmtime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="BYOUT_STATUS", property="byoutStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="UNPICK_STORE_ID", property="unpickStoreId", jdbcType=JdbcType.NUMERIC),
            @Result(column="SCANIN_STATUS", property="scaninStatus", jdbcType=JdbcType.NUMERIC),
            @Result(column="BEHALF_REMARK", property="behalfRemark", jdbcType=JdbcType.VARCHAR),
            @Result(column="ISDEFAULTSCAN", property="isdefaultscan", jdbcType=JdbcType.CHAR),
            @Result(column="STATUS", property="status", jdbcType=JdbcType.NUMERIC),
            @Result(column="RETINFO", property="retinfo", jdbcType=JdbcType.VARCHAR),
            @Result(column="SALE_TYPE", property="saleType", jdbcType=JdbcType.NUMERIC),
            @Result(column="billName", property="billName", jdbcType=JdbcType.VARCHAR),
            @Result(column="saleName", property="saleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="retsaleName", property="retsaleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="statusName", property="statusName", jdbcType=JdbcType.VARCHAR),
            @Result(column="storeName", property="storeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="storeCode", property="storeCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="blockName", property="blockName", jdbcType=JdbcType.VARCHAR),
            @Result(column="blockCode", property="blockCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="lcName", property="lcName", jdbcType=JdbcType.VARCHAR),
            @Result(column="lcCode", property="lcCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="lcDescription", property="lcDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="custName", property="custName", jdbcType=JdbcType.VARCHAR),
            @Result(column="custCode", property="custCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="custDescription", property="custDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="ID", property="items", javaType = List.class,many = @Many(select = "listById")),
    })
    RefundAudit selectByPrimaryKey(Long id);

    @Select({
            "select",
            "t1.ID,t1.AD_CLIENT_ID,t1.AD_ORG_ID,t1.OWNERID,t1.MODIFIERID,t1.CREATIONDATE,t1.MODIFIEDDATE,",
            "t1.ISACTIVE,t1.SHOWNAME,t1.M_RET_SALE_ID,t1.M_PRODUCT_ID,t1.M_PRODUCT2_ID,t1.MX1,t1.MX2,t1.MX3,",
            "t1.MX4,t1.MX5,t1.MX6,t1.MX7,t1.MX8,t1.MX9,t1.MX10,t1.MX11,t1.MX12,t1.MX13,t1.MX14,t1.MX15,",
            "t1.MX16,t1.MX17,t1.MX18,t1.MX19,t1.MX20,t1.MX21,t1.MX22,t1.MX23,t1.MX24,t1.TOT_QTY,t1.RN,",
            "t1.AMT_ACTUAL,t1.DESCRIPTION,t1.ISMODIFY,t1.QTY1,t1.QTYCAN,t1.M_COLOR_ID,t1.PRICEACTUAL2,",
            "t1.RET_REASON,t1.PRICEACTUAL,t2.name mProductCode,t3.name retReasonName",
            "from M_RET_SALECONF_MATRIX t1 left join M_PRODUCT t2 on t1.m_product_id=t2.id left join C_RET_QTYPE t3 on t1.RET_REASON=t3.id",
            "where t1.M_RET_SALE_ID= #{mRetSaleId,jdbcType=NUMERIC}"
    })
    @Results({
            @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC),
            @Result(column="AD_CLIENT_ID", property="adClientId", jdbcType=JdbcType.NUMERIC),
            @Result(column="AD_ORG_ID", property="adOrgId", jdbcType=JdbcType.NUMERIC),
            @Result(column="OWNERID", property="ownerid", jdbcType=JdbcType.NUMERIC),
            @Result(column="MODIFIERID", property="modifierid", jdbcType=JdbcType.NUMERIC),
            @Result(column="CREATIONDATE", property="creationdate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="MODIFIEDDATE", property="modifieddate", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="ISACTIVE", property="isactive", jdbcType=JdbcType.CHAR),
            @Result(column="SHOWNAME", property="showname", jdbcType=JdbcType.CHAR),
            @Result(column="M_RET_SALE_ID", property="mRetSaleId", jdbcType=JdbcType.NUMERIC),
            @Result(column="M_PRODUCT_ID", property="mProductId", jdbcType=JdbcType.NUMERIC),
            @Result(column="M_PRODUCT2_ID", property="mProduct2Id", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX1", property="mx1", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX2", property="mx2", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX3", property="mx3", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX4", property="mx4", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX5", property="mx5", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX6", property="mx6", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX7", property="mx7", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX8", property="mx8", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX9", property="mx9", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX10", property="mx10", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX11", property="mx11", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX12", property="mx12", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX13", property="mx13", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX14", property="mx14", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX15", property="mx15", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX16", property="mx16", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX17", property="mx17", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX18", property="mx18", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX19", property="mx19", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX20", property="mx20", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX21", property="mx21", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX22", property="mx22", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX23", property="mx23", jdbcType=JdbcType.NUMERIC),
            @Result(column="MX24", property="mx24", jdbcType=JdbcType.NUMERIC),
            @Result(column="TOT_QTY", property="totQty", jdbcType=JdbcType.NUMERIC),
            @Result(column="RN", property="rn", jdbcType=JdbcType.NUMERIC),
            @Result(column="AMT_ACTUAL", property="amtActual", jdbcType=JdbcType.NUMERIC),
            @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
            @Result(column="ISMODIFY", property="ismodify", jdbcType=JdbcType.VARCHAR),
            @Result(column="QTY1", property="qty1", jdbcType=JdbcType.NUMERIC),
            @Result(column="QTYCAN", property="qtycan", jdbcType=JdbcType.NUMERIC),
            @Result(column="M_COLOR_ID", property="mColorId", jdbcType=JdbcType.NUMERIC),
            @Result(column="PRICEACTUAL2", property="priceactual2", jdbcType=JdbcType.NUMERIC),
            @Result(column="RET_REASON", property="retReason", jdbcType=JdbcType.NUMERIC),
            @Result(column="PRICEACTUAL", property="priceactual", jdbcType=JdbcType.NUMERIC),
            @Result(column="retReasonName", property="retReasonName", jdbcType=JdbcType.VARCHAR),
            @Result(column="mProductCode", property="mProductCode", jdbcType=JdbcType.VARCHAR)
    })
    List<RefundAuditItem> listById(long mRetSaleId);

    @SelectProvider(type=RefundAuditSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.NUMERIC),
        @Result(column="AD_CLIENT_ID", property="adClientId", jdbcType=JdbcType.NUMERIC),
        @Result(column="AD_ORG_ID", property="adOrgId", jdbcType=JdbcType.NUMERIC),
        @Result(column="OWNERID", property="ownerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="MODIFIERID", property="modifierid", jdbcType=JdbcType.NUMERIC),
        @Result(column="CREATIONDATE", property="creationdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFIEDDATE", property="modifieddate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ISACTIVE", property="isactive", jdbcType=JdbcType.CHAR),
        @Result(column="DOCNO", property="docno", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOCTYPE", property="doctype", jdbcType=JdbcType.CHAR),
        @Result(column="BILLDATE", property="billdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SALESREP_ID", property="salesrepId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_STORE_ID", property="cStoreId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSTOMER_ID", property="cCustomerId", jdbcType=JdbcType.NUMERIC),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="AU_STATE", property="auState", jdbcType=JdbcType.CHAR),
        @Result(column="AU_PI_ID", property="auPiId", jdbcType=JdbcType.NUMERIC),
        @Result(column="AVG_DISCOUNT", property="avgDiscount", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_LINES", property="totLines", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_QTY", property="totQty", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMT_LIST", property="totAmtList", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMT_ACTUAL", property="totAmtActual", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_PERIOD_ID", property="cPeriodId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_ORIG_ID", property="cOrigId", jdbcType=JdbcType.NUMERIC),
        @Result(column="OUT_STATUS", property="outStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="IN_STATUS", property="inStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_QTYOUT", property="totQtyout", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMTOUT_LIST", property="totAmtoutList", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMTOUT_ACTUAL", property="totAmtoutActual", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_QTYIN", property="totQtyin", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMTIN_LIST", property="totAmtinList", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMTIN_ACTUAL", property="totAmtinActual", jdbcType=JdbcType.NUMERIC),
        @Result(column="DIFFREASON", property="diffreason", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATEOUT", property="dateout", jdbcType=JdbcType.NUMERIC),
        @Result(column="DATEIN", property="datein", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CUSTOMERUP_ID", property="cCustomerupId", jdbcType=JdbcType.NUMERIC),
        @Result(column="RETSALETYPE", property="retsaletype", jdbcType=JdbcType.CHAR),
        @Result(column="RETSALETYPE1", property="retsaletype1", jdbcType=JdbcType.CHAR),
        @Result(column="STATUSERID", property="statuserid", jdbcType=JdbcType.NUMERIC),
        @Result(column="STATUSTIME", property="statustime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INERID", property="inerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="INTIME", property="intime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="OUTERID", property="outerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="OUTTIME", property="outtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="C_RET_SALETYPE_ID", property="cRetSaletypeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="BOX_STATUS", property="boxStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_TRANWAY_JZ_ID", property="cTranwayJzId", jdbcType=JdbcType.NUMERIC),
        @Result(column="TRANWAYNO", property="tranwayno", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANWAY_PAY", property="tranwayPay", jdbcType=JdbcType.NUMERIC),
        @Result(column="OPERATOERID", property="operatoerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="OPER_STATUS", property="operStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PICKERID", property="pickerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISUF", property="isuf", jdbcType=JdbcType.CHAR),
        @Result(column="PROCESS_MODE", property="processMode", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMT_PRECOST", property="totAmtPrecost", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMTIN_PRECOST", property="totAmtinPrecost", jdbcType=JdbcType.NUMERIC),
        @Result(column="DISCOUNT", property="discount", jdbcType=JdbcType.NUMERIC),
        @Result(column="ISBOX", property="isbox", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_SALEDISTYPE_ID", property="cSaledistypeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="IMAGEURL", property="imageurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="C_CARGOTYPE_ID", property="cCargotypeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_STORE_LOCATION_ID", property="cStoreLocationId", jdbcType=JdbcType.NUMERIC),
        @Result(column="PRINTTIMES", property="printtimes", jdbcType=JdbcType.NUMERIC),
        @Result(column="PRINTOUTTIMES", property="printouttimes", jdbcType=JdbcType.NUMERIC),
        @Result(column="PRINTINTIMES", property="printintimes", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_CARGOINTYPE_ID", property="cCargointypeId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SCANSTATE", property="scanstate", jdbcType=JdbcType.CHAR),
        @Result(column="SENDQTY", property="sendqty", jdbcType=JdbcType.NUMERIC),
        @Result(column="SUBSENDQTY", property="subsendqty", jdbcType=JdbcType.NUMERIC),
        @Result(column="REALDATE", property="realdate", jdbcType=JdbcType.NUMERIC),
        @Result(column="IFMOVE", property="ifmove", jdbcType=JdbcType.CHAR),
        @Result(column="OUT_AU_STATE", property="outAuState", jdbcType=JdbcType.CHAR),
        @Result(column="OUT_AU_PI_ID", property="outAuPiId", jdbcType=JdbcType.NUMERIC),
        @Result(column="IN_AU_STATE", property="inAuState", jdbcType=JdbcType.CHAR),
        @Result(column="IN_AU_PI_ID", property="inAuPiId", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_AMT_PRICE", property="totAmtPrice", jdbcType=JdbcType.NUMERIC),
        @Result(column="AMT_DEDUCTION", property="amtDeduction", jdbcType=JdbcType.NUMERIC),
        @Result(column="PCK_STATUS", property="pckStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="PCHECKID", property="pcheckid", jdbcType=JdbcType.NUMERIC),
        @Result(column="PCHECKTIME", property="pchecktime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="TOT_AMTINVED", property="totAmtinved", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_QTYINVED", property="totQtyinved", jdbcType=JdbcType.NUMERIC),
        @Result(column="M_CRORETSALE_ID", property="mCroretsaleId", jdbcType=JdbcType.NUMERIC),
        @Result(column="IS_MAIN_RETSALE", property="isMainRetsale", jdbcType=JdbcType.CHAR),
        @Result(column="IS_CRORETSALEIN", property="isCroretsalein", jdbcType=JdbcType.CHAR),
        @Result(column="CARRIER", property="carrier", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHIPPING_REMARK", property="shippingRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_TOWMS", property="isTowms", jdbcType=JdbcType.CHAR),
        @Result(column="DEST_ADDR", property="destAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="M_BOX_ID", property="mBoxId", jdbcType=JdbcType.NUMERIC),
        @Result(column="QTY_BOX", property="qtyBox", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_TAX_AMT", property="totTaxAmt", jdbcType=JdbcType.NUMERIC),
        @Result(column="TOT_NOTAX_AMT", property="totNotaxAmt", jdbcType=JdbcType.NUMERIC),
        @Result(column="TAX_DIS", property="taxDis", jdbcType=JdbcType.NUMERIC),
        @Result(column="PAYMENTSTYLE", property="paymentstyle", jdbcType=JdbcType.CHAR),
        @Result(column="SCAN_STATUS", property="scanStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="BILLKIND", property="billkind", jdbcType=JdbcType.NUMERIC),
        @Result(column="CONTRACTNO_FILE", property="contractnoFile", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONFIRM_STATUS", property="confirmStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="CONFIRM_STATUSTIME", property="confirmStatustime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CONFIRM_STATUSERID", property="confirmStatuserid", jdbcType=JdbcType.NUMERIC),
        @Result(column="BILLNO", property="billno", jdbcType=JdbcType.VARCHAR),
        @Result(column="FISNO", property="fisno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BYIN_STATUS", property="byinStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="SCANNERID", property="scannerid", jdbcType=JdbcType.NUMERIC),
        @Result(column="C_SALER_ID", property="cSalerId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SCAN_INTIME", property="scanIntime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CONFIRM_INTIME", property="confirmIntime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELIVERY_CONFIRMTIME", property="deliveryConfirmtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="BYOUT_STATUS", property="byoutStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="UNPICK_STORE_ID", property="unpickStoreId", jdbcType=JdbcType.NUMERIC),
        @Result(column="SCANIN_STATUS", property="scaninStatus", jdbcType=JdbcType.NUMERIC),
        @Result(column="BEHALF_REMARK", property="behalfRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISDEFAULTSCAN", property="isdefaultscan", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.NUMERIC),
        @Result(column="RETINFO", property="retinfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALE_TYPE", property="saleType", jdbcType=JdbcType.NUMERIC),
            @Result(column="billName", property="billName", jdbcType=JdbcType.VARCHAR),
            @Result(column="saleName", property="saleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="retsaleName", property="retsaleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="statusName", property="statusName", jdbcType=JdbcType.VARCHAR),
            @Result(column="storeName", property="storeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="storeCode", property="storeCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="blockName", property="blockName", jdbcType=JdbcType.VARCHAR),
            @Result(column="blockCode", property="blockCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="lcName", property="lcName", jdbcType=JdbcType.VARCHAR),
            @Result(column="lcCode", property="lcCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="lcDescription", property="lcDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="custName", property="custName", jdbcType=JdbcType.VARCHAR),
            @Result(column="custCode", property="custCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="custDescription", property="custDescription", jdbcType=JdbcType.VARCHAR)
    })
    List<RefundAudit> selectByExample(RefundAuditExample example);

    @UpdateProvider(type=RefundAuditSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RefundAudit record, @Param("example") RefundAuditExample example);

    @UpdateProvider(type=RefundAuditSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RefundAudit record, @Param("example") RefundAuditExample example);
}